# Generated by Django 5.0.6 on 2024-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_capital', models.CharField(max_length=62)),
                ('population_capital', models.IntegerField()),
                ('short_description', models.TextField()),
                ('img_capital', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_land', models.CharField(max_length=62)),
                ('population_land', models.IntegerField()),
                ('flag', models.ImageField(upload_to='')),
            ],
        ),
    ]
