# Generated by Django 5.0.6 on 2024-05-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='land',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glav.land'),
        ),
    ]
